//! Thin wrappers over prost types generated from core/server/gen/libcore.proto (5A).
//! Same field numbers as Go; encode path materializes bools Core may dereference.

#![allow(clippy::all)]

use prost::Message;

// Generated by prost-build from libcore.proto at build time.
include!(concat!(env!("OUT_DIR"), "/libcore.rs"));

/// One live connection row for the UI table (subset of ConnectionMetaData).
#[derive(Debug, Clone, Default)]
pub struct ConnRow {
    pub id: String,
    /// Unix ms from Core `created_at` (0 if absent).
    pub created_at: i64,
    pub process: String,
    /// Full executable path when Core enricher resolved it (may be empty).
    pub process_path: String,
    /// OS process id when Core enricher resolved it (0 if unknown).
    pub process_id: u32,
    pub dest: String,
    pub domain: String,
    pub network: String,
    pub protocol: String,
    pub outbound: String,
    pub upload: i64,
    pub download: i64,
}

pub fn encode_string_field1(s: &str) -> Vec<u8> {
    // CheckConfig historically sent only field 1; keep helper for tests/smoke.
    let msg = LoadConfigReq {
        core_config: Some(s.to_string()),
        ..Default::default()
    };
    msg.encode_to_vec()
}

pub fn encode_load_config_core_json(json: &str) -> Vec<u8> {
    encode_string_field1(json)
}

/// LoadConfigReq: Core Start may dereference NeedExtraProcess, so encode it.
pub fn encode_load_config_req(core_json: &str, profile_id: Option<i32>) -> Vec<u8> {
    let msg = LoadConfigReq {
        core_config: Some(core_json.to_string()),
        disable_stats: Some(false),
        need_extra_process: Some(false),
        extra_no_out: Some(false),
        profile_id: Some(profile_id.unwrap_or(-1)),
        ..Default::default()
    };
    msg.encode_to_vec()
}

pub fn decode_error_resp(data: &[u8]) -> Option<String> {
    ErrorResp::decode(data).ok().and_then(|m| m.error).filter(|s| !s.is_empty())
}

pub fn decode_has_privilege(data: &[u8]) -> bool {
    IsPrivilegedResponse::decode(data)
        .ok()
        .and_then(|m| m.has_privilege)
        .unwrap_or(false)
}

pub fn decode_core_state(data: &[u8]) -> (bool, i32) {
    match CoreStateResponse::decode(data) {
        Ok(m) => (
            m.running.unwrap_or(false),
            m.profile_id.unwrap_or(-1),
        ),
        Err(_) => (false, -1),
    }
}

fn meta_to_row(m: ConnectionMetaData) -> ConnRow {
    ConnRow {
        id: m.id.unwrap_or_default(),
        created_at: m.created_at.unwrap_or(0),
        process: m.process.unwrap_or_default(),
        process_path: m.process_path.unwrap_or_default(),
        process_id: m.process_id.unwrap_or(0),
        dest: m.dest.unwrap_or_default(),
        domain: m.domain.unwrap_or_default(),
        network: m.network.unwrap_or_default(),
        protocol: m.protocol.unwrap_or_default(),
        outbound: m.outbound.unwrap_or_default(),
        upload: m.upload.unwrap_or(0),
        download: m.download.unwrap_or(0),
    }
}

/// QueryConnectionsResp active=1 + closed=2; short HTTP often lands in closed first.
pub fn decode_query_connections(data: &[u8]) -> Vec<ConnRow> {
    let Ok(resp) = QueryConnectionsResp::decode(data) else {
        return Vec::new();
    };
    let mut active: Vec<ConnRow> = resp.active.into_iter().map(meta_to_row).collect();
    let mut closed: Vec<ConnRow> = resp.closed.into_iter().map(meta_to_row).collect();
    // ponytail: 80 closed cap; raise if UI needs longer history
    const MAX_CLOSED: usize = 80;
    if closed.len() > MAX_CLOSED {
        closed = closed.split_off(closed.len() - MAX_CLOSED);
    }
    active.extend(closed);
    active
}

/// QueryStatsResp ups/downs maps — cumulative for tag `proxy` (session tunnel).
pub fn decode_query_stats_proxy(data: &[u8]) -> (i64, i64) {
    let Ok(resp) = QueryStatsResp::decode(data) else {
        return (0, 0);
    };
    let pick = |m: &std::collections::BTreeMap<String, i64>| -> i64 {
        if let Some(v) = m.get("proxy") {
            return *v;
        }
        m.iter()
            .filter(|(k, _)| k.as_str() != "direct" && !k.starts_with("dns-"))
            .map(|(_, v)| *v)
            .sum()
    };
    (pick(&resp.ups), pick(&resp.downs))
}

/// Shell SOT for Core TestCurrent URL (not empty — Core defaults to "").
pub const DEFAULT_URL_TEST: &str = "https://www.gstatic.com/generate_204";

/// One URL-test result row from Core `Test` / `QueryURLTest`.
#[derive(Debug, Clone, Default)]
pub struct UrlTestRow {
    pub tag: String,
    pub ms: i32,
    pub error: String,
}

/// Encode TestReq with test_current=true (live box proxy/default outbound only).
pub fn encode_test_req_current(url: &str, timeout_ms: i32, max_concurrency: i32) -> Vec<u8> {
    let url = if url.is_empty() {
        DEFAULT_URL_TEST.to_string()
    } else {
        url.to_string()
    };
    let msg = TestReq {
        test_current: Some(true),
        url: Some(url),
        test_timeout_ms: Some(if timeout_ms > 0 { timeout_ms } else { 3000 }),
        max_concurrency: Some(if max_concurrency > 0 {
            max_concurrency
        } else {
            1
        }),
        // Materialize bools Core may dereference.
        use_default_outbound: Some(false),
        ..Default::default()
    };
    msg.encode_to_vec()
}

pub fn decode_test_resp(data: &[u8]) -> Vec<UrlTestRow> {
    let Ok(resp) = TestResp::decode(data) else {
        return Vec::new();
    };
    resp.results
        .into_iter()
        .map(|r| UrlTestRow {
            tag: r.outbound_tag.unwrap_or_default(),
            ms: r.latency_ms.unwrap_or(0),
            error: r.error.unwrap_or_default(),
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn encode_load_has_bool_defaults() {
        let enc = encode_load_config_req("{}", Some(7));
        // field 3 need_extra_process key = (3<<3)|0 = 0x18, value 0
        assert!(
            enc.windows(2).any(|w| w == [0x18, 0x00]),
            "need_extra_process=false missing: {enc:?}"
        );
        let msg = LoadConfigReq::decode(enc.as_slice()).unwrap();
        assert_eq!(msg.core_config.as_deref(), Some("{}"));
        assert_eq!(msg.profile_id, Some(7));
        assert_eq!(msg.need_extra_process, Some(false));
    }

    #[test]
    fn roundtrip_string_field() {
        let enc = encode_string_field1("hi");
        let msg = LoadConfigReq::decode(enc.as_slice()).unwrap();
        assert_eq!(msg.core_config.as_deref(), Some("hi"));
    }

    fn hand_meta(id: &str, process: &str) -> ConnectionMetaData {
        ConnectionMetaData {
            id: Some(id.into()),
            created_at: Some(1_700_000_000_000),
            upload: Some(100),
            download: Some(200),
            outbound: Some("proxy".into()),
            network: Some("tcp".into()),
            dest: Some("1.1.1.1:443".into()),
            process: Some(process.into()),
            ..Default::default()
        }
    }

    #[test]
    fn decode_one_active_conn() {
        let resp = QueryConnectionsResp {
            active: vec![hand_meta("c1", "Chrome")],
            closed: vec![],
        };
        let rows = decode_query_connections(&resp.encode_to_vec());
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].id, "c1");
        assert_eq!(rows[0].created_at, 1_700_000_000_000);
        assert_eq!(rows[0].process, "Chrome");
        assert_eq!(rows[0].dest, "1.1.1.1:443");
        assert_eq!(rows[0].outbound, "proxy");
        assert_eq!(rows[0].upload, 100);
        assert_eq!(rows[0].download, 200);
        assert_eq!(rows[0].network, "tcp");
    }

    #[test]
    fn decode_closed_conn_included() {
        let resp = QueryConnectionsResp {
            active: vec![],
            closed: vec![hand_meta("c2", "curl")],
        };
        let rows = decode_query_connections(&resp.encode_to_vec());
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].id, "c2");
        assert_eq!(rows[0].process, "curl");
    }

    #[test]
    fn decode_stats_proxy_tag() {
        let mut ups = std::collections::BTreeMap::new();
        ups.insert("proxy".into(), 10);
        ups.insert("direct".into(), 99);
        let mut downs = std::collections::BTreeMap::new();
        downs.insert("proxy".into(), 20);
        let resp = QueryStatsResp { ups, downs };
        let (u, d) = decode_query_stats_proxy(&resp.encode_to_vec());
        assert_eq!((u, d), (10, 20));
    }

    #[test]
    fn encode_test_current_has_flags() {
        let enc = encode_test_req_current("", 3000, 1);
        let msg = TestReq::decode(enc.as_slice()).unwrap();
        assert_eq!(msg.test_current, Some(true));
        assert_eq!(msg.url.as_deref(), Some(DEFAULT_URL_TEST));
        assert_eq!(msg.test_timeout_ms, Some(3000));
        assert_eq!(msg.max_concurrency, Some(1));
    }

    #[test]
    fn decode_test_resp_error_and_ms() {
        let resp = TestResp {
            results: vec![UrlTestResp {
                outbound_tag: Some("proxy".into()),
                latency_ms: Some(42),
                error: Some("".into()),
            }],
        };
        let rows = decode_test_resp(&resp.encode_to_vec());
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].tag, "proxy");
        assert_eq!(rows[0].ms, 42);
        assert!(rows[0].error.is_empty());
    }
}
